### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S *.pgm -L crate,acn,ist,inout`

### CODE REVIEW

**Comment by szepeviktor** [comment]
This files is autogenerated.
https://github.com/CCExtractor/rusty_ffmpeg/blob/1963116e02b591a974456c96d83ee0d075d3d0dd/src/binding.rs#L1

**Comment by kianmeng** [comment]
@szepeviktor Should I close this PR since it was generated from other source?

**Comment by szepeviktor** [comment]
Yes, this file is generated from files outside this repository.

**Comment by szepeviktor** [comment]
Look for typos in https://github.com/FFmpeg/FFmpeg

**Pull request closed without merging**
